# Generated by Django 5.0.1 on 2024-02-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ткачев Михаил Сергеевич', verbose_name='ФИО')),
                ('position', models.CharField(default='Инженер-программистор', verbose_name='Должность')),
                ('hired', models.CharField(default='26.02.24', verbose_name='Дата трудоустройства')),
                ('salary', models.CharField(default='80000', verbose_name='Зарплата,р')),
            ],
        ),
    ]
