# Generated by Django 5.0.1 on 2024-02-04 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datab_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_employee',
            name='hired',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='c_employee',
            name='position',
            field=models.CharField(default='Инженер', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='c_employee',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=80000, max_digits=10, verbose_name='Зарплата,р'),
        ),
    ]
