# Generated by Django 5.0.1 on 2024-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datab_app', '0002_alter_c_employee_hired_alter_c_employee_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_employee',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y%m%d', verbose_name='Фотография'),
        ),
    ]
